### ISSUE TITLE
 undefined reference

### ISSUE THREAD

**Issue by turtiustrek** [rdbo/Memory#3]
Hello, 
I am trying to compile a test application in windows with  mingw-w64 and encountered a linking issue.
`g++ -Wall -Werror -DBUILDING_EXAMPLE_DLL -c  main.cpp  libs\mem\mem.cpp`
`g++ -shared -m64 -o main.dll mem.o main.o  -Wl,--out-implib,main.a`
![image](https://user-images.githubusercontent.com/12457839/89088708-2b764780-d3b3-11ea-945b-2d453bae02a6.png)
any help would be greatly appreciated.

**Comment by rdbo** [comment]
Can you compile a DLL with multiple source files or is this problem specific to the memory lib?

**Comment by turtiustrek** [comment]
Yes I have another test library which linked successfully but this is unable to.
test.h
`#ifndef TEST_H
#define TEST_H
int adds(int);
#endif`
test.cpp
`#include "test.h"
int adds(int a){
    return a;
}`
the adds function is called from main.cpp and it links and executes just as normal
Command line parameters:
`g++ -Wall -Werror -DBUILDING_EXAMPLE_DLL -c  main.cpp   libs\test\test.cpp`
`g++ -shared -m64 -o main.dll main.o test.o -Wl,--out-implib,main.a`
also the output is 64bit

**Comment by rdbo** [comment]
What is the code of main.cpp?

**Comment by turtiustrek** [comment]
https://www.throwbin.io/4FqNdIN

**Comment by rdbo** [comment]
I am on Linux rn and I also never used g++ on Windows, so I'll just give my last shot. Try this:
`g++ -c -m64 -fPIC main.cpp libs\test\test.cpp`
`g++ -shared -m64 -o main.dll main.o test.o`
If it doesn't work, then I'll install a Windows VM and check it out

**Comment by turtiustrek** [comment]
The commands do work and produce an injectable dll but upon using your library it gives the same error with the throwbin code above. 
I am using the following compiler for windows: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download

Windows 10 19041

**Comment by rdbo** [comment]
Just a note in case you want to finish what you're doing without having to wait for my response: it probably works on Visual Studio without any problems, as long as the project is set up properly.

**Comment by turtiustrek** [comment]
> Just a note in case you want to finish what you're doing without having to wait for my response

That's alright as I really want to compile this on GCC. 
it seems like MEM_COMPATIBLE does not even get defined at all.

**Comment by rdbo** [comment]
If MEM_COMPATIBLE is not defined then it could be:
1. Neither MEM_WIN nor MEM_LINUX is being defined
2. Neither MEM_86 not MEM_64 is being defined
Although most compilers (including gcc/g++ from what I've seen) set the defines by default, you could force MEM_WIN and MEM_64 to be set by putting this before including mem.hpp:
`#define _WIN32`
`#define _M_X64`

**Comment by turtiustrek** [comment]
Well with a bit of investigation, it turned out that neither `MEM_64` and `MEM_86` were being defined. Forcing that resulted in errors which looked like typos(maybe?) and were "fixed". The program compiles and runs just fine( with a bunch of warnings).
Updated linker: ` -shared -m64 -o main.dll mem.o main.o -Wl,--out-implib,main.a -L. -lPsapi`


in function `mem::int_t mem::ex::load_library(process_t process, lib_t libpath)`
the following changes were made:
![image](https://user-images.githubusercontent.com/12457839/89135454-94a8a880-d4e2-11ea-8f62-a9af74fc1f0d.png)

**Comment by rdbo** [comment]
You're right, that variable was supposed to be called "lib". I probably overwrote something on VSCode using CTRL+D. That is fixed now on the master branch (hopefully nothing else broke)

**Comment by turtiustrek** [comment]
>  (hopefully nothing else broke)

Absolutely.
Alright I am going to close this issue as it seems to be resolved (currently). Thanks for the amazing library! 
Edit: The mingw-w64 defines  both ```__MINGW32__``` and ```__MINGW64__```.The current one(in the library) however does not resolve for both ```MEM_64``` and ```MEM_86``` 

Edit 2: irrelevant but what is the size parameter in detour_trampoline?

**Comment by rdbo** [comment]
Thank you for letting me know about this MINGW definitions, gonna add them to the project.
Also, the size parameter in detour trampoline is used to return a gateway that contains the original bytes of the hooked area, so that you can call the original function through this gateway and return to the normal execution of the target program

**Comment by turtiustrek** [comment]
One more thing. It seems like the definitions on a 64-bit machine defines **both** ```__MINGW32__```  and ```__MINGW64__```. This may or may not cause problems.
